CREATE DATABASE runchallenge2026;
USE runchallenge2026;
CREATE TABLE runners(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),password VARCHAR(255),gender ENUM('male','female'),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE run_logs(id INT AUTO_INCREMENT PRIMARY KEY,runner_id INT,km FLOAT,log_date DATE,log_time TIME,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(runner_id) REFERENCES runners(id));